Feedback
lima-limon-inc/Conways-game-of-life pull request #4
Opened 2024-11-22 19:18 UTC by lima-limon-inc

Added feedback from seniors

2024-11-22 19:25 UTC, LeanSerra requested changes

2024-11-22 19:25 UTC, LeanSerra commented on src/conways.rs
> +        }
It is not necessary to create a string here, you can use `write!("")?` multiple times to get the same result

2024-11-23 16:16 UTC, lima-limon-inc commented on src/conways.rs
> +        }
Thanks!

2024-11-25 13:36 UTC, dsocolobsky approved these changes

2024-11-25 13:36 UTC, LeanSerra approved these changes
LGTM

2024-11-25 13:39 UTC, merged